# Generated by Django 6.0.8 on 2026-08-12 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_product_image_product_category'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
