# Generated by Django 6.0.8 on 2026-08-30 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orderitem_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
