# Generated by Django 6.0.8 on 2026-09-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_editorial_image_homepage_hero_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='category_description',
            field=models.TextField(blank=True, default='Explore our collections designed for every style, occasion and everyday moment.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='category_eyebrow',
            field=models.CharField(default='EXPLORE', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='category_title',
            field=models.CharField(default='Find Your Style.', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editorial_description',
            field=models.TextField(blank=True, default='Discover pieces designed to make every moment feel effortless.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editorial_eyebrow',
            field=models.CharField(default='THE COLLECTION', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='editorial_title',
            field=models.CharField(default='Elevate Your Everyday.', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='men_title',
            field=models.CharField(default='Men', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='new_arrivals_eyebrow',
            field=models.CharField(default='DISCOVER', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='new_arrivals_title',
            field=models.CharField(default='New Arrivals', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='women_title',
            field=models.CharField(default='Women', max_length=100),
        ),
    ]
