# Generated by Django 6.0.8 on 2026-09-02 10:09

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_category_description_and_more'),
        ('store', '0012_order_paystack_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='new_arrivals',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='featured_on_homepages', to='store.product'),
        ),
    ]
