# Generated by Django 6.0.8 on 2026-09-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_new_arrivals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='new_arrivals',
        ),
    ]
