# Generated by Django 6.0.8 on 2026-09-02 10:27

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_new_arrivals'),
        ('store', '0012_order_paystack_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageNewArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_arrivals', to='home.homepage')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_new_arrivals', to='store.product')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
